VentanillaElectronica/Controllers/AdministrativosController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Principal;
using System.Threading;
using System.Web.Mvc;
using System.Web.Security;
using VentanillaElectronica.App_Code;
using VentanillaElectronica.Models;

namespace VentanillaElectronica.Controllers
{
    [Authorize(Roles = "ADMINISTRATIVOS")]

    public class AdministrativosController : Controller
    {
        VentanillaDBContext db = new VentanillaDBContext();

        [HttpGet]
        public ActionResult Header()
        {
            Usuario usuario = (Usuario)HttpContext.User.Identity;
            return View(usuario);
        }

        [HttpGet]
        public ViewResult Dashboard(string currentFilter, int? page, int? EstatusFilter, string searchString)
        {
            EnumTramitesEstatus estatus = EnumTramitesEstatus.Solicitado;
            ViewBag.EstatusFilter = EnumTramitesEstatus.Solicitado;
            ViewBag.EstatusFilterInt = (int)EnumTramitesEstatus.Solicitado;

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            if (EstatusFilter != null)
            {
                if (Enum.IsDefined(typeof(EnumTramitesEstatus), EstatusFilter)) estatus = (EnumTramitesEstatus)EstatusFilter;
                ViewBag.EstatusFilter = estatus;
                ViewBag.EstatusFilterInt = (int)estatus;
            }

            VentanillaAdministrativo administrativo = db.Administrativos.Where(x => x.UserName == User.Identity.Name).FirstOrDefault();
            int[] programas = administrativo.AdministrativosPrograma.Select(x => (int)x.Programa).ToArray();

            List<VentanillaTramite> tramites;
            if (estatus == EnumTramitesEstatus.Solicitado)
            {
                tramites = db.Tramites.Where(x => (x.Estatus == estatus) && programas.Contains((int)x.Programa)).ToList();
            }
            else
            {
                tramites = db.Tramites.Where(x => x.Estatus == estatus && programas.Contains((int)x.Programa)).ToList();
            }
            if (!String.IsNullOrEmpty(searchString))
            {
                int[] alumnos = db.Alumnos.Where(y => y.Nombre.Contains(searchString)).Select(x => (int)x.Id).ToArray();
                tramites = tramites.Where(s => alumnos.Contains(s.VentanillaAlumnoId)).ToList();
            }

            if (estatus == EnumTramitesEstatus.Denegado || estatus == EnumTramitesEstatus.Aceptado)
            {
                tramites = tramites.OrderByDescending(x => x.FechaRegistro).OrderBy(x => x.Estatus).ToList();

            }
            else
            {
                tramites = tramites.OrderBy(x => x.FechaRegistro).OrderBy(x => x.Estatus).ToList();
            }

            int pageSize = int.Parse(System.Configuration.ConfigurationManager.AppSettings["PageSize"].ToString());
            int pageNumber = (page ?? 1);
            return View(tramites.ToPagedList(pageNumber, pageSize));
        }


        [HttpGet]
        [Authorize(Roles = "T407")]
        public ActionResult ReporteExamenUltimaOportunidadRevisados()
        {
            try
            {
                
                VentanillaAdministrativo administrativo = db.Administrativos.Where(x => x.UserName == User.Identity.Name).FirstOrDefault();

                int[] Permisos = administrativo.Permisos.Where(z => z.Modulo.Clave.Equals("T407")).Select(x => (int) x.RegionPrograma.Id).ToArray();
                
                List<VentanillaTramite> Tramites = db.Tramites.Where(x => x.Estatus == EnumTramitesEstatus.Solicitado && x.TramiteUltimaOportunidad.Estatus == EnumTramitesUltimaOportunidadEstatus.Revisado && x.Tipo == EnumTramitesTipo.UltimaOportunidad && (Permisos.Contains((int)  x.TramiteUltimaOportunidad.RegionPrograma.Id))).ToList();

                if (Tramites == null) return null;
                Tramites = Tramites.OrderBy(x => x.TramiteUltimaOportunidad.RegionPrograma.Region).OrderBy(y => y.TramiteUltimaOportunidad.FechaRevisado).OrderBy(z => z.TramiteUltimaOportunidad.RegionPrograma.Programa).ToList();


                byte[] memoryStream = PDFReporteUltimaOportunidadRevisado.createPDF(Tramites);
                if (memoryStream != null)
                {
                    return File(memoryStream, "application/pdf", "Reporte_Ultima_Oportunidad_SEA.pdf");
                }
                else
                {
                    return Json(new { Data = "memoryStream is null" }, JsonRequestBehavior.AllowGet);

                }

            }
            catch (Exception ex)
            {
                return Json(new { Data = ex.Message }, JsonRequestBehavior.AllowGet);
            }

        }
    }
}

VentanillaElectronica/Views/Administrativos/Dashboard.cshtml
@model PagedList.IPagedList<VentanillaElectronica.Models.VentanillaTramite>
@using PagedList.Mvc;
@using VentanillaElectronica.Models;

@{
    Layout = "~/Views/Shared/_LayoutContentAdministrativos.cshtml";
}


@using (Html.BeginForm("Dashboard", "Administrativos", FormMethod.Get, new { @class = "form-inline" }))
{

    <div class="col-md-7" style="float: right;">
        <div class="form-group">
            Buscar por nombre: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control" })

        </div>
        <input type="submit" value="Buscar" class="btn btn-info" />


        <div class="form-group" style="float: right;">
            Filtrar por:
            @Html.DropDownList("EstatusFilter", EnumHelper.GetSelectList(typeof(EnumTramitesEstatus)), new { @class = "form-control", onchange = "this.form.submit();" })

        </div>

    </div>

        <h2>Trámites</h2>
        <h4>
            <small class="text-danger">
                Mostrando: Estatus @ViewBag.EstatusFilter
                @if (ViewBag.CurrentFilter != null)
                {
                    <span>, Nombre contiene &lt;&lt; @ViewBag.CurrentFilter &gt;&gt;</span>
                }
            </small>
        </h4>
        <hr />
    if (Model.Count() > 0)
    {


        <table class="table table-striped">

            @foreach (var tramite in Model)
            {
                <tr>
                    <td nowrap>
                        @if (tramite.Tipo == EnumTramitesTipo.Alta || tramite.Tipo == EnumTramitesTipo.Baja || tramite.Tipo == EnumTramitesTipo.MovilidadEstudiantil)
                        {
                            <strong>Periodo @tramite.Periodo.Nombre</strong><br />
                            <small>@tramite.Tipo.Description()</small>
                        }
                        @if (tramite.Tipo == EnumTramitesTipo.UltimaOportunidad)
                        {
                        <strong>Programa @tramite.TramiteUltimaOportunidad.RegionPrograma.Value</strong><br />
                        <small>@tramite.Tipo.Description()</small>
                        }
                    </td>

                    @if (tramite.Tipo == EnumTramitesTipo.Alta)
                    {
                        <td width="100%">
                            NRC(@tramite.TramiteAlta.OfertaAlta.NRC) @tramite.TramiteAlta.OfertaAlta.Nombre<br />
                            <small>@tramite.Programa</small>
                        </td>

                    }

                    @if (tramite.Tipo == EnumTramitesTipo.MovilidadEstudiantil)
                    {
                        <td width="100%">
                            NRC(@tramite.TramiteMovilidad.OfertaMovilidad.NRC) @tramite.TramiteMovilidad.OfertaMovilidad.Nombre<br />
                            <small>@tramite.Programa</small>
                        </td>

                    }
                    @if (tramite.Tipo == EnumTramitesTipo.Baja)
                    {
                        <td width="100%">
                            NRC(@tramite.TramiteBaja.NRC) @tramite.TramiteBaja.ExperienciaEducativa<br />
                            <small>@tramite.TramiteBaja.BloqueTurno</small>
                        </td>
                    }

                    @if (tramite.Tipo == EnumTramitesTipo.UltimaOportunidad)
                    {
                        <td width="100%">
                            Experiencia Educativa: @tramite.TramiteUltimaOportunidad.ExperienciaEducativa<br />
                            <small>Docente: @tramite.TramiteUltimaOportunidad.Docente</small>
                        </td>
                    }

                    <td nowrap>
                        @if (@tramite.Estatus == VentanillaElectronica.Models.EnumTramitesEstatus.Solicitado)
                        {
                            <span class="label label-warning">@tramite.Estatus</span>  <span> el @Html.DisplayFor(x => tramite.FechaRegistro)</span>
                            <br /><small>Solicitado por @HttpUtility.HtmlDecode(Html.DisplayFor(x => tramite.Alumno.Nombre).ToHtmlString())</small>

                            if (@tramite.TramiteUltimaOportunidad.Estatus == VentanillaElectronica.Models.EnumTramitesUltimaOportunidadEstatus.Revisado)
                            {
                                <br /><span class="label label-default">@tramite.TramiteUltimaOportunidad.Estatus</span><span> el @Html.DisplayFor(x => tramite.TramiteUltimaOportunidad.FechaRevisado)</span>
                               <br /><small>Revisado por @HttpUtility.HtmlDecode(Html.DisplayFor(x => tramite.TramiteUltimaOportunidad.AdministrativoRevision.Nombre).ToHtmlString())</small>

                            }
                            if (@tramite.TramiteUltimaOportunidad.Estatus == VentanillaElectronica.Models.EnumTramitesUltimaOportunidadEstatus.DatosConsejoTecnico)
                            {
                             
                                <br /><span class="label label-default">@tramite.TramiteUltimaOportunidad.Estatus</span><span> el @Html.DisplayFor(x => tramite.TramiteUltimaOportunidad.FechaConsejoTecnico)</span>
                                <br /><small>Por @HttpUtility.HtmlDecode(Html.DisplayFor(x => tramite.TramiteUltimaOportunidad.AdministrativoRevision.Nombre).ToHtmlString())</small>

                            }

                        }
                        @if (@tramite.Estatus == VentanillaElectronica.Models.EnumTramitesEstatus.Aceptado)
                        {
                            <span class="label label-success">@tramite.Estatus</span><span> el @Html.DisplayFor(x => tramite.FechaAtencion)</span>
                            <br /><small>Solicitado por @HttpUtility.HtmlDecode(Html.DisplayFor(x => tramite.Alumno.Nombre).ToHtmlString())</small>
                            <br /><small>Atendido por @HttpUtility.HtmlDecode(Html.DisplayFor(x => tramite.Administrativo.Nombre).ToHtmlString())</small>

                        }
                        @if (@tramite.Estatus == VentanillaElectronica.Models.EnumTramitesEstatus.Denegado)
                        {
                            <span class="label label-danger">@tramite.Estatus</span><span> el @Html.DisplayFor(x => tramite.FechaAtencion)</span>
                            <br /><small>Solicitado por @HttpUtility.HtmlDecode(Html.DisplayFor(x => tramite.Alumno.Nombre).ToHtmlString())</small>
                            <br /><small>Atendido por @HttpUtility.HtmlDecode(Html.DisplayFor(x => tramite.Administrativo.Nombre).ToHtmlString())</small>

                        }

                       

                    </td>
                    <td>

                        <div class="dropdown">
                            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                Acciones
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                @if (@tramite.Estatus == VentanillaElectronica.Models.EnumTramitesEstatus.Solicitado)
                                {

                                    if (tramite.Tipo == EnumTramitesTipo.Baja)
                                    {
                                        <li> @Html.ActionLink("Atender", "Serve", "AdministrativosTramiteBaja", new { Id = tramite.Id }, new { })</li>

                                    }
                                    if (tramite.Tipo == EnumTramitesTipo.MovilidadEstudiantil)
                                    {
                                        <li>@Html.ActionLink("Atender", "Serve", "AdministrativosTramiteMovilidad", new { Id = tramite.Id }, new { })</li>
                                    }
                                    if (tramite.Tipo == EnumTramitesTipo.Alta)
                                    {
                                        <li>@Html.ActionLink("Atender", "Serve", "AdministrativosTramiteAltas", new { Id = tramite.Id }, new { })</li>
                                    }
                                    if (tramite.Tipo == EnumTramitesTipo.UltimaOportunidad)
                                    {
                                        <li>@Html.ActionLink("Ver detalles", "View", "AdministrativosTramiteUltimaOportunidad", new { Id = tramite.Id }, new { })</li>
                                    }
                                }

                                @if (@tramite.Estatus == VentanillaElectronica.Models.EnumTramitesEstatus.Aceptado || @tramite.Estatus == VentanillaElectronica.Models.EnumTramitesEstatus.Denegado)
                                {
                                    if (tramite.Tipo == EnumTramitesTipo.MovilidadEstudiantil)
                                    {
                                        <li> @Html.ActionLink("Ver detalles", "View", "AdministrativosTramiteMovilidad", new { Id = tramite.Id }, new { }) </li>
                                    }
                                    if (tramite.Tipo == EnumTramitesTipo.Baja)
                                    {
                                        <li> @Html.ActionLink("Ver detalles", "View", "AdministrativosTramiteBaja", new { Id = tramite.Id }, new { }) </li>

                                    }
                                    if (tramite.Tipo == EnumTramitesTipo.Alta)
                                    {
                                        <li> @Html.ActionLink("Ver detalles", "View", "AdministrativosTramiteAltas", new { Id = tramite.Id }, new { }) </li>

                                    }
                                    if (tramite.Tipo == EnumTramitesTipo.UltimaOportunidad)
                                    {
                                        <li> @Html.ActionLink("Ver detalles", "View", "AdministrativosTramiteUltimaOportunidad", new { Id = tramite.Id }, new { }) </li>

                                    }
                                }
                              



                                <li role="separator" class="divider"></li>
                                @if (User.IsInRole("ADMINISTRADORES"))
                                {
                                    if (tramite.Tipo == EnumTramitesTipo.MovilidadEstudiantil && (tramite.Estatus == EnumTramitesEstatus.Solicitado || tramite.Estatus == EnumTramitesEstatus.Denegado))
                                    {
                                        <li>@Html.ActionLink("Editar", "Edit", "AdministradoresTramiteMovilidad", new { Id = tramite.Id }, new { })</li>
                                    }


                                }
                            </ul>

                        </div>





                    </td>

                </tr>


            }
        </table>
        <br />
        if (Model.PageCount > 1)
        {

            <span>Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount con estatus: @ViewBag.EstatusFilter</span>

            @Html.PagedListPager(Model, page => Url.Action("Dashboard", new { page, EstatusFilter = ViewBag.EstatusFilterInt, currentFilter = ViewBag.CurrentFilter }))

        }



    }
    else
    {
        <p style="text-align: center; margin-top: 20px">
            <img src="~/Content/images/icon_sintramites.png" class="img-responsive center-block" alt="Sin trámites en curso"><br />
            <span style="color: #d6d6d6">Sin trámites encontrados con estatus: @ViewBag.EstatusFilter</span>
        </p>
    }


}

VentanillaElectronica/Views/Administrativos/Header.cshtml
@model VentanillaElectronica.Models.Usuario


<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>     
            <a class="navbar-brand" href="@Url.Action("Dashboard", "Administrativos")">Ventanilla electrónica</a>
       
        </div>
        <div id="navbar" class="navbar-collapse collapse">

          

            <ul class="nav navbar-nav">
               
@if (User.IsInRole("T407"))
{
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Reportes<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li class="dropdown-header">Examen de Última Oportunidad</li>
                        @if (User.IsInRole("T407"))
                        {
                        <li>@Html.ActionLink("Solicitudes revisadas para Consejo Técnico", "ReporteExamenUltimaOportunidadRevisados", "Administrativos", null, new { @class = "btn btn-info", target = "_blank" })</li>
                        }
                        <li role="separator" class="divider"></li>
                         </ul>
                </li>
}

                @if (User.IsInRole("ADMINISTRADORES"))
                {
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Usuarios y permisos<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                       
                        <li><a href="@Url.Action("Permisos", "Administradores")">Permisos de usuario</a></li>

                    </ul>
                </li>
                }


            </ul>
            <ul class="nav navbar-nav navbar-right">
                @*<li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Ayuda
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="@Url.Action("Sugerencias", "Ayuda")">Aportes y sugerencias</a></li>
                    </ul>
                </li>*@
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                        @Html.DisplayFor(m => m.Nombre)
                       
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a><strong>Administrativo</strong></a></li>
                        <li class="divider"></li>
                        <li><a href="@Url.Action("LogOut", "Home")">Cerrar sesión</a></li>
                    </ul>
                </li>
            </ul>
        </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
</nav>