VentanillaElectronica/Controllers/AdministradoresTramiteMovilidadController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Principal;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using VentanillaElectronica.App_Code;
using VentanillaElectronica.Models;

namespace VentanillaElectronica.Controllers
{
    [Authorize(Roles = "ADMINISTRADORES")]

    public class AdministradoresTramiteMovilidadController : Controller
    {
        VentanillaDBContext db = new VentanillaDBContext();


        [HttpGet]
        public ActionResult Edit(int? Id)
        {
            if (Id == null) return RedirectToAction("Dashboard", "Administrativos");

            VentanillaTramite tramite = db.Tramites.Where(x => x.Id == Id && (x.Estatus == EnumTramitesEstatus.Solicitado || x.Estatus == EnumTramitesEstatus.Denegado)).FirstOrDefault();

            if (tramite != null)
            {

                ModelViewVentanillaTramiteMovilidad tramiteModelView = new ModelViewVentanillaTramiteMovilidad();
                tramiteModelView.Administrativo = tramite.Administrativo;
                tramiteModelView.Alumno = tramite.Alumno;
                tramiteModelView.Estatus = tramite.Estatus;
                tramiteModelView.FechaActualizacion = tramite.FechaActualizacion;
                tramiteModelView.FechaAtencion = tramite.FechaAtencion;
                tramiteModelView.FechaRegistro = tramite.FechaRegistro;
                tramiteModelView.Id = tramite.Id;
                tramiteModelView.Observaciones = tramite.Observaciones;
                tramiteModelView.Periodo = tramite.Periodo;
                tramiteModelView.Programa = tramite.Programa;
                tramiteModelView.Tipo = tramite.Tipo;
                tramiteModelView.NewEstatus = tramite.Estatus;
                tramiteModelView.TramiteMovilidad = tramite.TramiteMovilidad;
                tramiteModelView.VentanillaAdministrativoId = tramite.VentanillaAdministrativoId;
                tramiteModelView.VentanillaAlumnoId = tramite.VentanillaAlumnoId;
                tramiteModelView.VentanillaPeriodoId = tramite.VentanillaPeriodoId;


                return View(tramiteModelView);
            }
            else { return RedirectToAction("Dashboard", "Administrativos"); }
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        [NoCache]
        public ActionResult Edit(int? Id, HttpPostedFileBase File, EnumTramitesEstatus NewEstatus)
        {
      
            if (Id == null) return RedirectToAction("Dashboard", "Administrativos");

            VentanillaTramite tramite = db.Tramites.Where(z => z.Id == Id && z.Estatus != EnumTramitesEstatus.Aceptado).FirstOrDefault();

            ModelViewTramitesEscenarios escenario = new ModelViewTramitesEscenarios();
            
            if (tramite != null)
            {
                if (File != null)
                {
                    string extension = Path.GetExtension(File.FileName);
                    string name = tramite.TramiteMovilidad.OfertaMovilidad.InscripcionMovilidad.Programa + "_NRC" + tramite.TramiteMovilidad.OfertaMovilidad.NRC + "_" + tramite.Alumno.UserName + "_" + String.Format("{0:ddMMyyyy}", DateTime.Now) + extension;
                    var path = Path.Combine(Server.MapPath("~/Uploads/Movilidad"), name);
                    File.SaveAs(path);
                    string URL = System.Configuration.ConfigurationManager.AppSettings["ServerApp"].ToString() + "Uploads/Movilidad/" + name;
                    tramite.TramiteMovilidad.Url = URL;
                }

                if (NewEstatus == EnumTramitesEstatus.Solicitado)
                {
                    tramite.Administrativo = null;
                    tramite.Estatus = EnumTramitesEstatus.Solicitado;
                    tramite.Observaciones = null;
                    tramite.FechaAtencion = null;
                    tramite.VentanillaAdministrativoId = null;
                }

                tramite.FechaActualizacion = DateTime.Now;
                db.Entry(tramite).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("View", "AdministrativosTramiteMovilidad", new { Id = tramite.Id });

            }
            return RedirectToAction("Dashboard", "Administrativos");

        }
           
    





}
}

VentanillaElectronica/Views/AdministradoresTramiteMovilidad/Edit.cshtml
@model VentanillaElectronica.Models.ModelViewVentanillaTramiteMovilidad 


@{
    Layout = "~/Views/Shared/_LayoutContentAdministrativos.cshtml";
}

   @using (Html.BeginForm("Edit", "AdministradoresTramiteMovilidad", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
   {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(p => p.Id)

        <div class="jumbotron">
            <h2>Trámite de movilidad estudiantil</h2>
            <h4>Edición del trámite</h4>
            <hr />
            <div class="row">
                <div class="col-xs-12 col-md-3">
                    <img src="~/Content/images/icon_sintramites.png" class="img-responsive center-block" alt="Editando">
                </div>
                <div class="col-xs-12 col-md-9">
                    @Html.Partial("ViewDetails", Model)
                </div>
            </div>
            <hr />
            @Html.ActionLink("Cancelar", "Dashboard", "Administrativos", null, new { @class = "btn btn-default" })
            <a id="Submit" class="btn btn-primary">Actualizar</a>
        </div>
   }

<!-- Modal -->
<div class="modal fade" id="ModalConfirmation" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Editar trámite de movilidad</h4>
            </div>
            <div class="modal-body">
                ¿La información a almacenar es correcta?<br /><br/>
                Si se cambia de un estado <span class="label label-danger">Denegado</span> a un estado <span class="label label-warning">Solicitado</span> la información de la persona que atendió el trámite se eleminará.
</div>
            <div class="modal-footer">
                <button data-dismiss="modal" type="button" class="btn btn-danger">Cancel</button>
                <button id="btnContinueDelete" type="button" class="btn btn-primary">Aceptar</button>
            </div>
        </div>
    </div>
</div>

  
@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {

            $('#Submit').click(function () {

                if ($('form').valid()) {
                    $('#ModalConfirmation').modal('show');
                }

            });


            $('#btnContinueDelete').click(function () {
                $('form').submit();

            });
        });
    </script>
}

VentanillaElectronica/Views/AdministradoresTramiteMovilidad/Serve.cshtml
@model VentanillaElectronica.Models.ModelViewServeTramitesMovilidad
@using VentanillaElectronica.Models;


@{
    Layout = "~/Views/Shared/_LayoutContentAdministrativos.cshtml";
}

@using (Html.BeginForm("Serve", "AdministrativosTramiteMovilidad", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(p => p.Id)

    if (Model.Estatus == VentanillaElectronica.Models.EnumTramitesEstatus.Solicitado)
    {



            <h2>Trámite de movilidad estudiantil</h2>
            <h4>Solicitado, atendiendo trámite</h4>
            <hr />
            <div class="row">

                <div class="col-xs-12 col-md-6">


                    <div class="form-group">

                        @Html.LabelFor(a => a.Administrativo, new { @class = "col-sm-3 control-label", @for = "Atendido por" })
                        <div class="col-sm-9">

                            <div class="input-group">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
                                @Html.TextArea("AtendidoPor", (HttpUtility.HtmlDecode(Html.DisplayFor(a => a.Administrativo.Nombre).ToHtmlString()) + Environment.NewLine + Html.DisplayFor(a => a.Administrativo.Email) + Environment.NewLine + Html.DisplayFor(a => a.Administrativo.Telefono)), 5, 120, new { @readonly = "readonly", @class = "form-control" })
                            </div>
                        </div>
                    </div>

                    <div class="form-group">

                        @Html.LabelFor(a => a.EstatusServe, new { @class = "col-sm-3 control-label", @for = "Estatus" })
                        <div class="col-sm-9">
                            <div class="input-group">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-record"></span></span>
                                @Html.DropDownListFor(x => x.EstatusServe, EnumHelper.GetSelectList(typeof(EnumTramitesEstatusServe)), "",new { @class = "form-control" })
                            </div>
                            @Html.ValidationMessageFor(a => a.EstatusServe)
                        </div>
                    </div>




                        <div class="form-group">

                            @Html.LabelFor(a => a.Observaciones, new { @class = "col-sm-3 control-label", @for = "Observaciones" })
                            <div class="col-sm-9">
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-bookmark"></span></span>
                                    @Html.TextArea("Observaciones", HttpUtility.HtmlDecode(Html.DisplayFor(a => a.Observaciones).ToHtmlString()), 5, 120, new { @class = "form-control" })
                                </div>
                                @Html.ValidationMessageFor(a => a.Observaciones)
                            </div>
                        </div>

                        <hr />

                        @Html.ActionLink("Cancelar", "Dashboard", "Administrativos", null, new { @class = "btn btn-default" })
                        <a id="Submit" class="btn btn-primary">Guardar</a>

                    </div>


                <div class="col-xs-12 col-md-6 jumbotron alert-warning">

                    <div class="form-group">

                        @Html.LabelFor(a => a.Estatus, new { @class = "col-sm-3 control-label", @for = "Estatus" })
                        <div class="col-sm-9">

                            @if (Model.Estatus == VentanillaElectronica.Models.EnumTramitesEstatus.Solicitado)
                            {
                                <span class="label label-warning">@Model.Estatus</span>
                            }
                            @if (@Model.Estatus == VentanillaElectronica.Models.EnumTramitesEstatus.Aceptado)
                            {
                                <span class="label label-success">@Model.Estatus</span>

                            }@if (@Model.Estatus == VentanillaElectronica.Models.EnumTramitesEstatus.Denegado)
                            {
                                <span class="label label-danger">@Model.Estatus</span>
                            }

                        </div>

                    </div>

                    <div class="form-group">

                        @Html.LabelFor(a => a.OfertaMovilidad.InscripcionMovilidad.Periodo, new { @class = "col-sm-3 control-label", @for = "Periodo" })
                        <div class="col-sm-9">
                            <div class="input-group">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-time"></span></span>
                                @Html.TextBoxFor(a => a.OfertaMovilidad.InscripcionMovilidad.Periodo.Nombre, new { disabled = "disabled", Value = Html.DisplayFor(a => a.OfertaMovilidad.InscripcionMovilidad.Periodo.Nombre), @class = "form-control" })
                            </div>
                        </div>

                    </div>

                    <div class="form-group">

                        @Html.LabelFor(a => a.OfertaMovilidad.Nombre, new { @class = "col-sm-3 control-label", @for = "Experiencia educativa" })
                        <div class="col-sm-9">
                            <div class="input-group">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-book"></span></span>
                                @Html.TextBoxFor(a => a.OfertaMovilidad.Nombre, new { disabled = "disabled",  Value = ("NRC (" + Html.DisplayFor(a => a.OfertaMovilidad.NRC) + ") " + Html.DisplayFor(a => a.OfertaMovilidad.Nombre)), @class = "form-control" })
                            </div>
                        </div>

                    </div>

                    <div class="form-group">

                        @Html.LabelFor(a => a.FechaRegistro, new { @class = "col-sm-3 control-label", @for = "Fecha registro" })
                        <div class="col-sm-9">
                            <div class="input-group">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-time"></span></span>
                                @Html.TextBoxFor(a => a.FechaRegistro, new { disabled = "disabled",  Value = Html.DisplayFor(a => a.FechaRegistro), @class = "form-control" })
                            </div>
                        </div>

                    </div>

                    <div class="form-group">

                        @Html.LabelFor(a => a.Alumno, new { @class = "col-sm-3 control-label", @for = "Alumno" })
                        <div class="col-sm-9">

                            <div class="input-group">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
                                @Html.TextArea("Alumno", (HttpUtility.HtmlDecode(Html.DisplayFor(a => a.Alumno.Nombre).ToHtmlString()) + Environment.NewLine + Html.DisplayFor(a => a.Alumno.Region) + Environment.NewLine + Html.DisplayFor(a => a.Alumno.Programa) + Environment.NewLine + "Email institucional: " + Model.Alumno.Email + Environment.NewLine + "Email alterno: " + Model.Alumno.EmailAlterno + Environment.NewLine + "Teléfono celular: +52 " + Html.DisplayFor(a => a.Alumno.Telefono)), 7, 120, new { disabled = "disabled", @class = "form-control" })
                            </div>
                        </div>
                    </div>

                    <div class="form-group">

                        @Html.LabelFor(a => a.Url, new { @class = "col-sm-3 control-label", @for = "Documento comprobatorio" })
                        <div class="col-sm-9">


                            <a href="@Model.Url" target="_blank" title="Documento comprobatorio" class="btn btn-default">
                                <span class="glyphicon glyphicon-download"></span> Descargar documento comprobatorio
                            </a>
                        </div>

                    </div>

                </div>

            </div>
           
      

    }
}




<!-- Modal -->
<div class="modal fade" id="ModalConfirmation" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Trámite de movilidad</h4>
            </div>
            <div class="modal-body">
                ¿La información a almacenar es correcta?
            </div>
            <div class="modal-footer">
                <button data-dismiss="modal" type="button" class="btn btn-danger">Cancel</button>
                <button id="btnContinueDelete" type="button" class="btn btn-primary">Aceptar</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {

            $('#Submit').click(function () {

                if ($('form').valid()) {
                    $('#ModalConfirmation').modal('show');
                }

            });


            $('#btnContinueDelete').click(function () {
                $('form').submit();

            });
        });
    </script>
}

VentanillaElectronica/Views/AdministradoresTramiteMovilidad/ViewDetails.cshtml
@model VentanillaElectronica.Models.ModelViewVentanillaTramiteMovilidad

@using VentanillaElectronica.Models;


@using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
{

   

    <div class="form-group">

        @Html.LabelFor(a => a.Periodo, new { @class = "col-sm-2 control-label", @for = "Periodo" })
        <div class="col-sm-10">
            <div class="input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-time"></span></span>
                @Html.TextBoxFor(a => a.Periodo.Nombre, new { @readonly = "readonly", Value = Html.DisplayFor(a => a.Periodo.Nombre), @class = "form-control" })
            </div>
        </div>

    </div>

    <div class="form-group">

        @Html.LabelFor(a => a.TramiteMovilidad.OfertaMovilidad.Nombre, new { @class = "col-sm-2 control-label", @for = "Experiencia educativa" })
        <div class="col-sm-10">
            <div class="input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-book"></span></span>
                @Html.TextBoxFor(a => a.TramiteMovilidad.OfertaMovilidad.Nombre, new { @readonly = "readonly", Value = ("NRC (" + Html.DisplayFor(a => a.TramiteMovilidad.OfertaMovilidad.NRC) + ") " + Html.DisplayFor(a => a.TramiteMovilidad.OfertaMovilidad.Nombre)), @class = "form-control" })
            </div>
        </div>

    </div>

    <div class="form-group">

        @Html.LabelFor(a => a.FechaRegistro, new { @class = "col-sm-2 control-label", @for = "Fecha registro" })
        <div class="col-sm-10">
            <div class="input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-time"></span></span>
                @Html.LabelFor(a => a.FechaRegistro, new { @readonly = "readonly", Value = Html.DisplayFor(a => a.FechaRegistro), @class = "form-control" })
            </div>
        </div>

    </div>
    
    <div class="form-group">

        @Html.LabelFor(a => a.Alumno, new { @class = "col-sm-2 control-label", @for = "Alumno" })
        <div class="col-sm-10">

            <div class="input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
                @Html.TextArea("Alumno", (HttpUtility.HtmlDecode(Html.DisplayFor(a => a.Alumno.Nombre).ToHtmlString()) + Environment.NewLine + Html.DisplayFor(a => a.Alumno.Region) + Environment.NewLine + Html.DisplayFor(a => a.Alumno.Programa) + Environment.NewLine + "Email institucional: " + Model.Alumno.Email + Environment.NewLine + "Email alterno: " + Model.Alumno.EmailAlterno + Environment.NewLine + "Teléfono celular: +52 " + Html.DisplayFor(a => a.Alumno.Telefono)), 7, 120, new { @readonly = "readonly", @class = "form-control" })
            </div>
        </div>
    </div>
   
  


    if (Model.Estatus == VentanillaElectronica.Models.EnumTramitesEstatus.Aceptado || Model.Estatus == VentanillaElectronica.Models.EnumTramitesEstatus.Denegado)
    {
        <hr />
        <div class="form-group">

            @Html.LabelFor(a => a.FechaAtencion, new { @class = "col-sm-2 control-label", @for = "Fecha de atención" })
            <div class="col-sm-10">
                <div class="input-group">
                    <span class="input-group-addon"><span class="glyphicon glyphicon-time"></span></span>
                    @Html.LabelFor(a => a.FechaAtencion, new { @readonly = "readonly", Value = Html.DisplayFor(a => a.FechaAtencion), @class = "form-control" })
                </div>
            </div>
        </div>

        <div class="form-group">

            @Html.LabelFor(a => a.Administrativo, new { @class = "col-sm-2 control-label", @for = "Atendido por" })
            <div class="col-sm-10">

                <div class="input-group">
                    <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
                    @Html.TextArea("AtendidoPor", (HttpUtility.HtmlDecode(Html.DisplayFor(a => a.Administrativo.Nombre).ToHtmlString()) + Environment.NewLine + Html.DisplayFor(a => a.Administrativo.Email) + Environment.NewLine + Html.DisplayFor(a => a.Administrativo.Telefono)), 5, 120, new { @readonly = "readonly", @class = "form-control" })
                </div>
            </div>
        </div>

        <div class="form-group">

            @Html.LabelFor(a => a.Observaciones, new { @class = "col-sm-2 control-label", @for = "Observaciones" })
            <div class="col-sm-10">
                <div class="input-group">
                    <span class="input-group-addon"><span class="glyphicon glyphicon-bookmark"></span></span>
                    @Html.TextArea("Observaciones", HttpUtility.HtmlDecode(Html.DisplayFor(a => a.Observaciones).ToHtmlString()), 5, 120, new { @readonly = "readonly", @class = "form-control" })
                </div>
            </div>
        </div>

    }

    <hr />
    <div class="form-group">

        @Html.LabelFor(a => a.TramiteMovilidad.Url, new { @class = "col-sm-2 control-label", @for = "Documento comprobatorio" })
        <div class="col-sm-10">


            <a href="@Model.TramiteMovilidad.Url" target="_blank" title="Documento comprobatorio" class="btn btn-default">
                <span class="glyphicon glyphicon-download"></span> Descargar documento comprobatorio
            </a>
        </div>

    </div>

    <div class="form-group">
        @Html.LabelFor(a => a.File, new { @class = "col-sm-2 control-label", @for = "File" })
        <div class="col-sm-10">


            @Html.TextBoxFor(a => a.File, new { type = "file", maxFileSize = 100, language = "es", data_show_preview = "false", data_show_upload = "false", data_allowed_file_extensions = "[\"pdf\", \"docx\",\"jpg\",\"jpeg\",\"png\"]", data_show_caption = "true", @placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(a => a.File).ToHtmlString()), @class = "file" })
            <em><small>Sólo se admiten archivos en formato PDF, DOCX, JPG-JPEG, PNG.</small></em><br />
            @Html.ValidationMessageFor(a => a.File)

        </div>
    </div>

    <div class="form-group">

        @Html.LabelFor(x => x.Estatus, new { @class = "col-sm-2 control-label", @for = "Estatus" })
        <div class="col-sm-10">

            @if (Model.Estatus == VentanillaElectronica.Models.EnumTramitesEstatus.Solicitado)
            {
                <span class="label label-warning">@Model.Estatus</span>
            }
            @if (@Model.Estatus == VentanillaElectronica.Models.EnumTramitesEstatus.Aceptado)
            {
                <span class="label label-success">@Model.Estatus</span>

            }@if (@Model.Estatus == VentanillaElectronica.Models.EnumTramitesEstatus.Denegado)
            {
                <span class="label label-danger">@Model.Estatus</span>
            }

        </div>

    </div>
    <div class="form-group">

        @Html.LabelFor(x => x.NewEstatus, new { @class = "col-sm-2 control-label", @for = "NewEstatus" })
        <div class="col-sm-10">
            <div class="input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-record"></span></span>
                @if (Model.Estatus == EnumTramitesEstatus.Solicitado)
                {
                    @Html.DropDownListFor(a => a.NewEstatus, EnumHelper.GetSelectList(typeof(EnumTramitesEditSolicitado)), new { @class = "form-control" })

                }
                else
                {
                    @Html.DropDownListFor(a => a.NewEstatus, EnumHelper.GetSelectList(typeof(EnumTramitesEdit)), new { @class = "form-control" })
                }
            </div>
        </div>
    </div>





}